#!/bin/bash
set -euo pipefail

# Autor: Leonardo Bruno
# Versão: 4.0
# data: 19/05/2025

# O que esse script faz?
# Ele instala o gerenciador-jdk na pasta do usuário corrente.


echo "Iniciando instalação..."

# Cria diretório temporário para download
TEMP_DIR=$(mktemp -d)

# Nome arquivo
NOME_ARQUIVO="gerenciador-node"

# URL para download
URL_DOWNLOAD="https://raw.githubusercontent.com/souza-lb/gerenciador-node/refs/heads/main/gerenciador-node"

# Efetua o download do arquivo do gerenciador
wget -q "$URL_DOWNLOAD" -O "$TEMP_DIR/$NOME_ARQUIVO"

# Concede permissão de execução
chmod +x "$TEMP_DIR/$NOME_ARQUIVO"

# Criar diretório .bin na pasta home do usuário
mkdir -p $HOME/.bin

# Copiar o arquivo gerenciador para o diretório .bin
cp "$TEMP_DIR/$NOME_ARQUIVO" $HOME/.bin/

# Adicionar o PATH ao .bashrc se não existir
if ! grep -q "# CONFIG_GERENCIADOR_AUTO" $HOME/.bashrc; then
    echo -e "\n"
    echo -e  "\n# CONFIG_GERENCIADOR_AUTO" >> $HOME/.bashrc 
    echo 'export PATH="$PATH:$HOME/.bin"' >> $HOME/.bashrc
    echo "# ------------------------------" >> $HOME/.bashrc
fi

echo "Limpando arquivos temporários..."
rm -rf "$TEMP_DIR"
echo "Limpeza concluída!"

# Mensagem final
echo "Instalação concluída!"
echo "Para aplicar as alterações, execute:"
echo "source ~/.bashrc"
